# Generated by Django 4.1.7 on 2023-03-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishtodarija',
            name='examples',
            field=models.TextField(blank=True),
        ),
    ]
