# Generated by Django 4.1.7 on 2023-03-26 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictio', '0002_englishtodarija_examples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishtodarija',
            name='examples',
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_text', models.TextField()),
                ('english_to_darija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictio.englishtodarija')),
            ],
        ),
    ]
