# Generated by Django 4.1.7 on 2023-03-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictio', '0003_remove_englishtodarija_examples_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishtodarija',
            name='part_of_speech',
            field=models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective')], default='noun', max_length=20),
        ),
    ]
