# Generated by Django 4.1.7 on 2023-03-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictio', '0005_englishtodarija_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishtodarija',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
    ]
