# Generated by Django 4.1.7 on 2023-03-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictio', '0006_englishtodarija_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishtodarija',
            name='plurality',
            field=models.CharField(choices=[('neutral', ''), ('singular', 'Singular'), ('plural', 'Plural')], default='neutral', max_length=20),
        ),
    ]
