# Generated by Django 4.1.7 on 2023-03-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictio', '0007_englishtodarija_plurality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishtodarija',
            name='plurality',
            field=models.CharField(choices=[('', ''), ('singular', 'Singular'), ('plural', 'Plural')], default='', max_length=20),
        ),
    ]
