# Generated by Django 4.1.7 on 2023-03-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('image_choice', 'Image Choice'), ('text_choice', 'Text Choice'), ('textinputquestion', 'Text Input')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
